[general]

import = [
   "~/.config/alacritty/themes/tokyonight_moon.toml"
]


[window]

	#decorations = "Full" 

	opacity = 0.95
	#blur = true

	dynamic_title = true



[scrolling]

	history = 25000

[font]

	size = 12
	normal = { family = "SauceCodeProNerdFontMono", style = "Regular" }
	bold = { family = "SauceCodeProNerdFontMono", style = "Bold" }
	italic = { family = "SauceCodeProNerdFontMono", style = "Italic" }
	bold_italic = { family = "SauceCodeProNerdFontMono", style = "Bold Italic" }




# [colors]














[terminal]



[mouse]


	hide_when_typing = true



